# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1100, 849)

        MainWindow.setWindowFlags(
            QtCore.Qt.Window
            | QtCore.Qt.CustomizeWindowHint
            | QtCore.Qt.WindowTitleHint
            | QtCore.Qt.WindowCloseButtonHint
        )

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 1061, 791))
        self.label.setText("")

        self.movie = QtGui.QMovie("./media/animated4.webp")
        self.label.setMovie(self.movie)
        self.movie.start()

        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 50, 310, 91))
        self.label_2.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n"
            "color: rgb(255, 255, 255);\n"
            'font: 75 24pt "MS Shell Dlg 2";'
        )
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(235, 220, 190, 61))  # left-up button
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(455, 220, 190, 61))
        self.pushButton_2.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(
            QtCore.QRect(680, 220, 190, 61)
        )  # right-up button
        self.pushButton_3.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(
            QtCore.QRect(680, 320, 190, 61)
        )  # right-down button
        self.pushButton_4.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(455, 320, 190, 61))
        self.pushButton_5.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(
            QtCore.QRect(235, 320, 190, 61)
        )  # left-down button
        self.pushButton_6.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:#6320EE;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:20%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #8075FF;\n"
            "    \n"
            "}"
        )
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 460, 161, 61))
        self.pushButton_7.setStyleSheet(
            "QPushButton {\n"
            "color:white;\n"
            "background-color:red;\n"
            'font: 16pt "MS Shell Dlg 2";\n'
            "border-radius:10%;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F55536;\n"
            "    \n"
            "}"
        )
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "File Management "))
        self.pushButton.setText(_translate("MainWindow", "Show Files"))
        self.pushButton_2.setText(_translate("MainWindow", "Create File"))
        self.pushButton_3.setText(_translate("MainWindow", "Create Folder"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete Folder"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete File"))
        self.pushButton_6.setText(_translate("MainWindow", "Show Directory"))
        self.pushButton_7.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
